---
name: CI for Foodgram

on:
  push:
    branches: [ master ]

jobs:

  tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-builtins flake8-import-order pep8-naming flake8-broken-line flake8-quotes
        pip install -r backend/requirements.txt


    - name: Test with flake8
      run: |
        python -m flake8 backend/

  copy_infra_to_server:
    name: Copy docker-compose.yml and nginx.conf
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v2

    - name: Create projects directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.HOST_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd projects
          sudo rm -rf foodgram
          mkdir -p foodgram

    - name: Copy files
      uses: garygrossgarten/github-action-scp@release
      with:
          local: infra/
          remote: /${{ secrets.HOST_USER }}/projects/foodgram/
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          privateKey: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.HOST_PASS }}

  build_push_backend_to_DockerHub:
    name: Building back image and pushing it to Docker Hub
    runs-on: ubuntu-20.04
    needs: tests
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Push "foodgram/backend" to DockerHub
      uses: docker/build-push-action@v2
      with:
        context: backend/
        push: true
        tags: ${{ secrets.DOCKER_USER }}/foodgram_back:latest

  build_push_frontend_to_DockerHub:
    name: Building front image and pushing it to Docker Hub
    runs-on: ubuntu-20.04
    needs: tests
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Push "foodgram/frontend" to DockerHub
      uses: docker/build-push-action@v2
      with:
        context: frontend/
        push: true
        tags: ${{ secrets.DOCKER_USER }}/foodgram_front:latest

  deploy:
    runs-on: ubuntu-20.04
    needs:
      - copy_infra_to_server
      - build_push_backend_to_DockerHub
      - build_push_frontend_to_DockerHub
    steps:
    - name: remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.HOST_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd projects/foodgram/
          touch .env
          echo DEBUG=${{ secrets.DEBUG }} >> .env
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
          echo ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }} >> .env
          echo CSRF_TRUSTED_ORIGINS=${{ secrets.CSRF_TRUSTED_ORIGINS }} >> .env
          echo DB_ENGINE=${{ secrets.DB_ENGINE }} >> .env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_PORT=${{ secrets.DB_PORT }} >> .env

          sudo docker-compose stop
          sudo docker rm foodgram_frontend_1
          sudo docker rm foodgram_backend_1
          sudo docker rmi ${{ secrets.DOCKER_USER }}/foodgram_front
          sudo docker rmi ${{ secrets.DOCKER_USER }}/foodgram_back
          sudo docker-compose up -d
  
  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} успешно выполнен!
...
